name: astrocyteCalcium
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - napari
  - tk
  - opencv
  - ipywidgets
  - pillow
  - scikit-image
  - tifffile
  - pip:
    - pip
    - umap-learn
    - connected-components-3d
